name: Deploys

on:
  push

jobs:
  surge-deploy:
    name: Surge deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [ 'imperative' ]
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - run: yarn install

#      - run: yarn workspace ${{ matrix.package }} lint
#      - run: yarn workspace ${{ matrix.package }} test

      - run: |
          yarn workspace ${{ matrix.package }} build
          zip -r ${{ matrix.package }} packages/${{ matrix.package }}/dist

#      - name: Deploy to ${{ matrix.package }} to surge (latest)
#        uses: dswistowski/surge-sh-action@v1
#        env:
#          latest_domain: perottidev-tic-tac-toe-${{ matrix.package }}.surge.sh
#        with:
#          domain: ${{ env.latest_domain }}
#          project: ./packages/${{ matrix.package }}/dist
#          login: ${{ secrets.surge_login }}
#          token: ${{ secrets.surge_token }}

      - name: Calculate GITHUB SHA SHORT
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Set staging url
        id: staging_env
        run: echo "::set-output name=staging_url::perottidev-tic-tac-toe-${{ matrix.package }}-${{ steps.vars.outputs.sha_short }}.surge.sh"

      - name: Deploy to ${{ matrix.package }} to surge (sha)
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: ${{ steps.staging_env.outputs.staging_url }}
          project: ./packages/${{ matrix.package }}/dist
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}

      - name: Tag
        id: tag
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: main
          release_strategy: none
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          release_name: |
            [${{ matrix.package }}] Release  ${{ github.ref }}"
          body: |
            Project hosted on https://surge.sh:
            https://${{ steps.staging_env.outputs.staging_url }}
          prerelease: true

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./packages/${{ matrix.package }}/${{ matrix.package }}.zip
          asset_name: ${{ matrix.package }}.zip
          asset_content_type: application/zip
