name: Validations

on:
  - push
  - pull_request

jobs:
  test:
    name: Test packages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [ 'imperative' ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: yarn install
      - name: test
        run: yarn workspace ${{ matrix.package }} test

  lint:
    name: Lint packages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [ 'imperative' ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: yarn install
      - name: lint
        run: yarn workspace ${{ matrix.package }} lint
